[package]
name = "jimhillr-github-io"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
passionfruitdev = { version = "0", features = ["website"]}
leptos = { version = "0.5.2", features = ["csr"] }
include_dir = "0.7.3"
markdown = "1.0.0-alpha"
