backend:
  name: git-gateway
  branch: main
media_folder: "public/images"
public_folder: "images"
collections:
  - name: "en"
    label: "US English"
    folder: "content/en"
    create: true
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }